name: Analyze admin0911

on:
  workflow_dispatch:

jobs:
  install-package:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Install admin0911@1.1.1
        run: npm install admin0911@1.1.1

  upload-package:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Download package tarball
        run: |
          npm pack admin0911@1.1.1
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: admin0911-1.1.1
          path: "*.tgz"
