name: Install mbt Compromised Package

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner OS to install on"
        required: true
        type: choice
        options:
          - ubuntu
          - windows
          - macos
          - both
        default: "both"

permissions: read-all

jobs:
  install-mbt-ubuntu:
    if: inputs.runner == 'ubuntu' || inputs.runner == 'both'
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install mbt 1.2.48
        continue-on-error: true
        run: |
          npm install mbt@1.2.48

      - name: Verify package install and version
        continue-on-error: true
        run: |
          node -e "const pkg = require('./node_modules/mbt/package.json'); console.log('mbt version:', pkg.version);"

      - run: sleep 4m

  install-mbt-windows:
    if: inputs.runner == 'windows' || inputs.runner == 'both'
    runs-on: windows-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install mbt 1.2.48
        continue-on-error: true
        run: |
          npm install mbt@1.2.48

      - name: Verify package install and version
        continue-on-error: true
        run: |
          node -e "const pkg = require('./node_modules/mbt/package.json'); console.log('mbt version:', pkg.version);"

      - run: sleep 2m

  install-mbt-macos:
    if: inputs.runner == 'macos' || inputs.runner == 'both'
    runs-on: macos-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install mbt 1.2.48
        continue-on-error: true
        run: |
          npm install mbt@1.2.48

      - name: Verify package install and version
        continue-on-error: true
        run: |
          node -e "const pkg = require('./node_modules/mbt/package.json'); console.log('mbt version:', pkg.version);"

      - run: sleep 2m
