name: Analyze simonecorsi/mawesome

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Run semantic-release-action
        uses: simonecorsi/mawesome@v2.2.0

      - name: wait
        if: always()
        run: sleep 30s
